services:
  - docker
env:
  global:
    - DOCKER_PRODUCER_NAME=leonardiwagner/eks-producer:0.0.1
    - DOCKER_CONSUMER_NAME=leonardiwagner/eks-consumer:0.0.1
before_install:
 - ls
 - echo $DOCKER_PRODUCER_NAME
 - docker build -t $DOCKER_PRODUCER_NAME app-producer/
 - docker build -t $DOCKER_CONSUMER_NAME app-consumer/
script:
  - docker run --rm $DOCKER_PRODUCER_NAME sh -c "npm i && npm test"
  - docker run --rm $DOCKER_CONSUMER_NAME sh -c "npm i && npm test"
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $DOCKER_PRODUCER_NAME
  - docker push $DOCKER_CONSUMER_NAME