apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1 #same number of nodes
  selector:
    matchLabels:
      app: eks-app
      tier: consumer
  template:
    metadata:
      labels:
        app: eks-app
        tier: consumer
    spec:
      containers:
        - name: app-consumer
          image: leonardiwagner/eks-consumer:0.0.1
          command: ["npm", "start"]
          env:
            - name: HTTP_PORT
              value: "3003"
          ports:
            - containerPort: 3003