apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: eks-app
spec:
  selector:
    app: eks-app
    tier: consumer
  type: LoadBalancer
  ports:
    - port: 3003 #port on node
      targetPort: 3003  #port on pod