apiVersion: v1
kind: Service
metadata:
  name: app-consumer-lb
spec:
  selector:
    app: app-consumer
  type: LoadBalancer
  ports:
    - port: 30300 #port on node
      targetPort: 3003 #port on pod