apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: app-consumer
  type: LoadBalancer
  ports:
    - port: 3003 #port on node
      targetPort: 3003  #port on pod