apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1 #same number of nodes
  selector:
    matchLabels:
      app: eks-app
      tier: producer
  template:
    metadata:
      labels:
        app: eks-app
        tier: producer
    spec:
      containers:
        - name: app-producer
          image: leonardiwagner/eks-producer:0.0.1
          imagePullPolicy: Always
          command: ["npm", "start"]
          env:
            - name: CONSUMER_ADDRESS
              value: "http://consumer:3003"
