apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: app-producer
  type: LoadBalancer
  ports:
    - port: 3001 #port on node
      targetPort: 3001  #port on pod